name: mlops-exaple-tensorflow-regression
on:
  [push]   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
         python-version: 3.12.0  # Version de Python 

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train and Evaluate Model
        run: |
          python model.py

          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md

          echo "\n## Model Performance" >> report.md
          echo "Model performance metrics are on the plot below." >> report.md

          # Assuming cml-publish and cml-send-comment are commands from some tool
          cml-publish model_results.png --md >> report.md

          cml-send-comment report.md

      - name: Commit and Push Report
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Add model evaluation report"
          git push
